[package]
name = "delta-client"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.18.0", features = ["v4"] }
delta-lib ={ path = "../delta-lib" }
log = "0.4.27"
env_logger = "0.11.8"
indicatif = "0.18.0"